In [10]:
import numpy as np
import pandas as pd

def LU_decomposition(A):
    L=np.zeros([m,m])
    U= np.zeros([m,m])
    for i in range(m):
        L[i][i]=1
        if i==0:
            U[0][0]=A[0][0]
        #u1就是A的第一行
            for j in range(1,m):
                U[0][j]=A[0][j]
                L[j][0]=A[j][0]/U[0][0]
        else:
            #求U ui为A-l1u1-l2u2-...liui的第i 行
            for j in range (0,m):
                temp=0
                for k in range(0,i):
                    temp+=L[i][k]*U[k][j]
                U[i][j]=A[i][j]-temp
            #求L li为A-l1u1-l2u2-...liui的第i 列除以U[i][i]
            for j in range (0,m):
                temp=0
                for k in range(0,i):
                    temp+=L[j][k]*U[k][i]
                L[j][i]=(A[j][i]-temp)/U[i][i]
    return L,U        
if __name__ == '__main__': 
    m = int(input())
    A = [[] for i in range(m)]
    for i in range(m):
        line = input().split(' ')
        for j in range(len(line)):
            A[i].append(int(line[j]))
    L,U=LU_decomposition(A)
    print(L,'\n',U)

4
5 3 -1 3
0 1 1 -2
-5 -3 4 -4
0 1 1 0
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  1.  0.]
 [ 0.  1.  0.  1.]] 
 [[ 5.  3. -1.  3.]
 [ 0.  1.  1. -2.]
 [ 0.  0.  3. -1.]
 [ 0.  0.  0.  2.]]


5
1 2 3 5 6
3 5 7 3 6
2 5 7 2 5
3 5 2 4 3
3 5 2 4 3
